
####################################################################################
# Generated by PlanAhead 14.7 built on 'Fri Sep 27 19:29:51 MDT 2013' by 'xbuild'
####################################################################################


####################################################################################
# Constraints from file : 'pines.ucf'
####################################################################################


#net "sysclk_p" loc = "H19" | IOSTANDARD = DIFF_SSTL15_DCI | #Bank 38
#MRCC input
#net "sysclk_n" loc = "G18" | IOSTANDARD = DIFF_SSTL15_DCI | #Diff.
#Rterm R2 DNP

#200Mhz clock input
#set_property PACKAGE_PIN H19 [get_ports clk_in]
#set_property IOSTANDARD LVCMOS18 [get_ports clk_in]
#create_clock -name clk_in -period 30.000 [get_ports clk_in]
#set_property IOSTANDARD DIFF_SSTL15 [get_ports clk]

#differential clk only needs one constraint
create_clock -period 5.0 [get_ports clk_in1_p]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1_p]] 0.042910000000000004
set_property PHASESHIFT_MODE WAVEFORM [get_cells -hierarchical *adv*]

#north pin
set_property PACKAGE_PIN AR40 [get_ports sw2]
set_property IOSTANDARD LVCMOS18 [get_ports sw2]

#LED outputs
set_property PACKAGE_PIN AM39 [get_ports {LEDs[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LEDs[0]}]
set_property PACKAGE_PIN AN39 [get_ports {LEDs[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LEDs[1]}]
set_property PACKAGE_PIN AR37 [get_ports {LEDs[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LEDs[2]}]
set_property PACKAGE_PIN AT37 [get_ports {LEDs[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LEDs[3]}]
set_property PACKAGE_PIN AR35 [get_ports {LEDs[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LEDs[4]}]
set_property PACKAGE_PIN AP41 [get_ports {LEDs[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LEDs[5]}]
set_property PACKAGE_PIN AP42 [get_ports {LEDs[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LEDs[6]}]
set_property PACKAGE_PIN AU39 [get_ports {LEDs[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LEDs[7]}]

#UART
set_property PACKAGE_PIN AU33 [get_ports rx]
set_property IOSTANDARD LVCMOS18 [get_ports rx]
set_property PACKAGE_PIN AU36 [get_ports tx]
set_property IOSTANDARD LVCMOS18 [get_ports tx]